
/**
 * Mapping of UK postal area codes to location names
 * Used for translating postcodes to geographic regions
 */
export const postalAreaMapping: Record<string, string> = {
  // London postal areas
  'e': 'london east', 
  'ec': 'london central', 
  'wc': 'london central', 
  'n': 'london north', 
  'nw': 'london north', 
  'se': 'london south', 
  'sw': 'london south', 
  'w': 'london west',
  
  // England postal areas
  'b': 'birmingham', 'ba': 'bath', 'bb': 'blackburn', 'bd': 'bradford',
  'bh': 'bournemouth', 'bl': 'bolton', 'bn': 'brighton', 'br': 'bromley area',
  'bs': 'bristol', 'ca': 'carlisle', 'cb': 'cambridge', 'cf': 'cardiff',
  'ch': 'chester', 'cm': 'chelmsford', 'co': 'colchester', 'cr': 'croydon',
  'cv': 'coventry', 'cw': 'crewe', 'da': 'dartford', 'dd': 'dundee',
  'de': 'derby', 'dg': 'dumfries', 'dh': 'durham', 'dl': 'darlington',
  'dn': 'doncaster', 'dt': 'dorchester', 'dy': 'dudley', 'eh': 'edinburgh',
  'en': 'enfield', 'ex': 'exeter', 'fk': 'falkirk', 'fy': 'blackpool',
  'g': 'glasgow', 'gl': 'gloucester', 'gu': 'guildford', 'ha': 'harrow',
  'hd': 'huddersfield', 'hg': 'harrogate', 'hp': 'hemel hempstead', 'hr': 'hereford',
  'hs': 'hebrides', 'hu': 'hull', 'ig': 'ilford', 'ip': 'ipswich',
  'iv': 'inverness', 'kt': 'kingston upon thames', 'l': 'liverpool',
  'la': 'lancaster', 'le': 'leicester', 'll': 'llandudno', 'ln': 'lincoln',
  'ls': 'leeds', 'm': 'manchester', 'me': 'rochester', 'mk': 'milton keynes',
  'ml': 'motherwell', 'ne': 'newcastle', 'ng': 'nottingham', 'nn': 'northampton',
  'np': 'newport', 'nr': 'norwich', 'ol': 'oldham', 'ox': 'oxford',
  'pa': 'paisley', 'pe': 'peterborough', 'ph': 'perth', 'pl': 'plymouth',
  'po': 'portsmouth', 'pr': 'preston', 'rg': 'reading', 'rh': 'redhill',
  's': 'sheffield', 'sa': 'swansea', 'sg': 'stevenage',
  'sk': 'stockport', 'sl': 'slough', 'sm_': 'sutton', 'sn': 'swindon',  // Changed 'sm' to 'sm_' to avoid duplicate
  'so': 'southampton', 'sp': 'salisbury', 'sr': 'sunderland', 'ss': 'southend-on-sea',
  'st': 'stoke-on-trent', 'sy': 'shrewsbury', 'ta': 'taunton',
  'td': 'galashiels', 'tf': 'telford', 'tn': 'tunbridge wells', 'tq': 'torquay',
  'tr': 'truro', 'ts': 'middlesbrough', 'tw': 'twickenham', 'ub': 'southall',
  'wa': 'warrington', 'wd': 'watford',
  'wf': 'wakefield', 'wn': 'wigan', 'wr': 'worcester', 'ws': 'walsall',
  'wv': 'wolverhampton', 'yo': 'york', 'zy': 'swansea valley',
  
  // Northern Ireland postal areas
  'bt': 'belfast',
  'bt1': 'belfast city centre',
  'bt2': 'belfast city centre',
  'bt4': 'belfast east',
  'bt5': 'belfast east',
  'bt6': 'belfast east',
  'bt7': 'belfast south',
  'bt8': 'belfast south',
  'bt9': 'belfast south',
  'bt11': 'belfast west',
  'bt12': 'belfast west',
  'bt13': 'belfast north',
  'bt14': 'belfast north',
  'bt15': 'belfast north',
  'bt16': 'belfast east',
  'bt17': 'belfast west',
  'bt18': 'holywood',
  'bt19': 'bangor',
  'bt20': 'bangor',
  'bt23': 'newtownards',
  'bt26': 'hillsborough',
  'bt27': 'lisburn',
  'bt28': 'lisburn',
  'bt29': 'crumlin',
  'bt30': 'downpatrick',
  'bt31': 'castlewellan',
  'bt32': 'banbridge',
  'bt33': 'newcastle',
  'bt34': 'newry',
  'bt35': 'newry',
  'bt36': 'newtownabbey',
  'bt37': 'newtownabbey',
  'bt38': 'carrickfergus',
  'bt39': 'ballyclare',
  'bt40': 'larne',
  'bt41': 'antrim',
  'bt42': 'ballymena',
  'bt43': 'ballymena',
  'bt44': 'ballymena',
  'bt45': 'magherafelt',
  'bt46': 'maghera',
  'bt47': 'londonderry',
  'bt48': 'londonderry',
  'bt49': 'limavady',
  'bt51': 'coleraine',
  'bt52': 'coleraine',
  'bt53': 'ballymoney',
  'bt54': 'ballycastle',
  'bt55': 'portstewart',
  'bt56': 'portrush',
  'bt57': 'bushmills',
  'bt60': 'armagh',
  'bt61': 'armagh',
  'bt62': 'craigavon',
  'bt63': 'craigavon',
  'bt64': 'craigavon',
  'bt65': 'craigavon',
  'bt66': 'craigavon',
  'bt67': 'craigavon',
  'bt68': 'caledon',
  'bt69': 'aughnacloy',
  'bt70': 'dungannon',
  'bt71': 'dungannon',
  'bt74': 'enniskillen',
  'bt75': 'fivemiletown',
  'bt76': 'clogher',
  'bt77': 'augher',
  'bt78': 'omagh',
  'bt79': 'omagh',
  'bt80': 'cookstown',
  'bt81': 'castlederg',
  'bt82': 'strabane',
  'bt92': 'enniskillen',
  'bt93': 'enniskillen',
  'bt94': 'enniskillen',
  
  // Republic of Ireland postal areas (simplified)
  'd': 'dublin',
  'd1': 'dublin',
  'd2': 'dublin',
  'd3': 'dublin',
  'd4': 'dublin',
  'd5': 'dublin',
  'd6': 'dublin',
  'd7': 'dublin',
  'd8': 'dublin',
  'd9': 'dublin',
  'd10': 'dublin',
  'd11': 'dublin',
  'd12': 'dublin',
  'd13': 'dublin',
  'd14': 'dublin',
  'd15': 'dublin',
  'd16': 'dublin',
  'd17': 'dublin',
  'd18': 'dublin',
  'd20': 'dublin',
  'd22': 'dublin',
  'd24': 'dublin',
  'a': 'dublin area',
  'c': 'cork',
  'e_roi': 'waterford',  // Changed 'e' to 'e_roi' to avoid duplicate with London 'e'
  'f': 'galway',
  'h': 'limerick',
  'k': 'kilkenny',
  'n_roi': 'monaghan',   // Changed 'n' to 'n_roi' to avoid duplicate with London 'n'
  't': 'tipperary',
  'v': 'wexford',
  'w_roi': 'wicklow',    // Changed 'w' to 'w_roi' to avoid duplicate with London 'w'
  'y': 'clare',
  
  // Additional areas to improve coverage
  'ab': 'aberdeen',
  'al': 'st albans',
  'ky': 'kirkcaldy',
  'ze': 'shetland',
  'im': 'isle of man',
  'je': 'jersey',
  'gg': 'guernsey',
  'pk': 'perth',
  'ka': 'kilmarnock',
  'dt_add': 'dorchester extra',  // Changed 'dt' to 'dt_add' to avoid duplicate
  'zb': 'carmarthen',
  'zc': 'bridgend',
  'sm_add': 'sutton extra',      // Changed 'sm' to 'sm_add' to avoid duplicate
  'by': 'trowbridge',
  'ay': 'ayr'
};
